# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-24 20:01
from __future__ import unicode_literals

import courses.models
from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django_enumfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseOffering',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prerequisites', models.TextField(blank=True, max_length=500, verbose_name='prerequisites')),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('post', django_enumfield.db.fields.EnumField(default=2, enum=courses.models.PostChoices, verbose_name='post')),
                ('department', django_enumfield.db.fields.EnumField(default=0, enum=courses.models.DepartmentChoices, verbose_name='department')),
            ],
            options={
                'verbose_name': 'Professor',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ReportCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_mark', models.IntegerField(null=True, verbose_name='first mark')),
                ('second_mark', models.IntegerField(null=True, verbose_name='second mark')),
                ('third_mark', models.IntegerField(null=True, verbose_name='third mark')),
                ('forth_mark', models.IntegerField(null=True, verbose_name='forth mark')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('year_in_university', django_enumfield.db.fields.EnumField(default=1, enum=courses.models.YearChoices, verbose_name='year')),
                ('group', models.IntegerField(verbose_name='group')),
                ('department', django_enumfield.db.fields.EnumField(default=0, enum=courses.models.DepartmentChoices, verbose_name='department')),
                ('courses', models.ManyToManyField(to='courses.CourseOffering')),
            ],
            options={
                'verbose_name': 'Student',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='reportcard',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Student'),
        ),
        migrations.AddField(
            model_name='courseoffering',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Professor'),
        ),
    ]
